openapi: "3.0.1"
info:
  version: "1.0.0"
  title: "Esperanto Wikipedia Raw WikiText Access for AI Assistants"

paths:
  /w/index.php:
    get:
      tags:
        - "Raw WikiText"
      summary: "Get the raw WikiText for a page in Esperanto Wikipedia."
      operationId: "get_esperanto_raw_wikitext"
      parameters:
        - name: "title"
          in: "query"
          description: "Page title for which the raw WikiText is required. Use the title as it appears in the URL, with underscores instead of spaces. Use percent-encoding for non-standard characters. Example: `Esperanto`."
          required: true
          schema:
            type: "string"
        - name: "action"
          in: "query"
          description: "Action parameter to retrieve raw WikiText. Always set this to 'raw'."
          required: true
          schema:
            type: "string"
            default: "raw"
      responses:
        200:
          description: "Raw WikiText content as a .php file"
        default:
          description: "Error"

components:
  schemas: {}

tags:
  - name: "Raw WikiText"
    description: "Raw WikiText of an Esperanto Wikipedia page. Example URL: https://eo.wikipedia.org/w/index.php?title=Esperanto&action=raw"

servers:
  - url: "https://eo.wikipedia.org"
